spring:
  application:
    name: fifteen-dollar-challenge
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.springframework: debug
    com.bb.fifteen: info
    org.hibernate:
      type:
        descriptor.sql: trace
