spring:
  application:
    name: fifteen-dollar-challenge
  datasource:
# 로컬 H2
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
# 로컬 MySQL
#    url: jdbc:mysql://localhost:3306/fifteen
#    username: app
#    password: 1q2w3e4R!@
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
# 로컬 H2
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.springframework: debug
    com.bb.fifteen: info
    org.hibernate:
      type:
        descriptor.sql: trace
